// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkgz7pQeZvQfNfkf_OECial92RW3XTjwY',
    appId: '1:3096193251:android:4678cdc9235a5d072bbdd6',
    messagingSenderId: '3096193251',
    projectId: 'flashchat-e2ad4',
    storageBucket: 'flashchat-e2ad4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASzhuPN2Jef7c0mR3zW7ZyCLmKpZkoezM',
    appId: '1:3096193251:ios:21c80560a5633ddc2bbdd6',
    messagingSenderId: '3096193251',
    projectId: 'flashchat-e2ad4',
    storageBucket: 'flashchat-e2ad4.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASzhuPN2Jef7c0mR3zW7ZyCLmKpZkoezM',
    appId: '1:3096193251:ios:ff3ac669a43c60152bbdd6',
    messagingSenderId: '3096193251',
    projectId: 'flashchat-e2ad4',
    storageBucket: 'flashchat-e2ad4.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
